server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://quangly.mysql.database.azure.com:3306/BackEnd_DA?useSSL=true&requireSSL=true
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: quanglee
    password: domixi@2024
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: bk.manarate@gmail.com
    password: rjrx mmkv skew aqit
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 36000 #seconds
  refreshable-duration: 360000 #seconds

cloudinary:
  cloud_name: "dkamugos5"
  api_key: "699183452242579"
  api_secret: "1pFbBUoout8BGSR0jf2zidml8s8"

logging:
  level:
    root: INFO